config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :bookings
  resources :services
  resources :pets
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/checkout', to: 'pages#checkout'
  get '/about', to: 'pages#about'
  get '/find', to: 'pages#find'
  get '/my_services', to: 'services#my_services'
  root to: 'pages#home'
  get 'profile/:id', to: 'pages#profile', :as => :profile

  get 'success/', to: 'bookings#success' 
  get 'my_profile/', to: 'pages#my_profile', :as => :my_profile

end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :user
    validates :name, length: { in: 5..20, message: "Must be between 5 and 20 characters"}
    validates :description, length: { in: 10..120, message: "Must be between 10 and 120 characters"}
    validates :price, numericality: { greater_than: 0, less_than: 1000 }

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  load_and_authorize_resource
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :my_services, :show]
  # GET /services
  # GET /services.json

  def index 
    redirect_to :root
  end

  # Retrieves only services owned by the current user to be displayed

  def my_services
    @allservices = Service.includes(:user).all
    @services = []
    
    @allservices.each { |service| 
      if service.user_id == current_user.id
        @services << service
      end
      }
  end

  # GET /services/1
  # GET /services/1.json
  # Looks a bit weird... but allows the user to create a new booking from services#show by pulling in 
  # Booking.new for the button, and pulling in pets owned by the current user for the drop down form
  def show
    @booking = Booking.new
    @my_pets = []
    @pets = Pet.includes(:user).all
    @pets.each { |pet| 
      if pet.user_id == current_user.id
        @my_pets << pet 
      end
    }
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  # Sets user_id to current_user id
  def create
    @service = Service.new(service_params)
    @service.user_id = current_user.id

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :description, :price, :user_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_booking.html.erb
<%= form_with(model: @booking, local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <%= form.hidden_field :service_id, value: @service.id %>


  <div class="field">

    <%= form.collection_select(:pet_id, @my_pets, :id, :name, { :prompt => "Book for..."}, { :class => "form-control"})%>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_form.html.erb
<div class="form-signin text-center container" >
<%= image_tag("logo.png", class: "mb-4")%>
<h2 class="h3 mb-3 font-weight-normal" >Enter details</h2>
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name , class: "form-control", placeholder: "Service name" %>
  </div>
  <div class="field">

    <%= form.text_area :description, class: "form-control", placeholder: "Service Description"  %>
  </div>

  <div class="field">
    <%= form.text_field :price, class: "form-control", placeholder: "Price"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/my_services.html.erb
<p id="notice"><%= notice %></p>

  <h2>Services</h2>

<div class="services-list">
  <div class="services-header row mb-3">
    <div class="col-md-3">
      <strong>Service</strong>
    </div>
    <div class="col-md-6">
      <strong>Description</strong>
    </div>
    <div class="col-md-3">
      <strong>Price</strong>
    </div>
  </div>

<% @services.each do |service| %>
  <%= link_to service do %>
      <div class="row mb-3 service">
        <div class="col-md-3">
          <%= service.name %>
        </div>
        <div class="col-md-6">
          <%= service.description %>
        </div>
        <div class="col-md-3">
          <%= number_to_currency(service.price) %>
      </div>
  </div>
    <%end%>
  <% end %>
</div>

  <br>

  <%= link_to 'New Service', new_service_path, class: "btn btn-outline-info btn-lg" %>

app/views/services/new.html.erb
<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
  <p>
    <strong>Name:</strong>
    <%= @service.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @service.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(@service.price) %>
  </p>

  <% if current_user.id != @service.user_id%>
  <p>
    <strong>Service offered by:</strong>
    <%= @service.user.fname %>
  </p>
  <% end %>

  <% if can? :manage, @service %>
  <%= link_to 'Edit', edit_service_path(@service) %> <br>
  <%= link_to 'Delete', @service, method: :delete, data: { confirm: 'Delete this Service?' } %><br>
  <%= link_to 'Add another service', new_service_path %><br>
  <%= link_to 'Back', my_profile_path %> <br>
  <%end%>

  <% if current_user.id != @service.user_id%>
<div class="show-service">
  <%= render 'booking', service: @service %>
</div>
  <%= link_to 'Back', :back %> <br>
  <% end %>