config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :bookings
  resources :services
  resources :pets
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/checkout', to: 'pages#checkout'
  get '/about', to: 'pages#about'
  get '/find', to: 'pages#find'
  get '/my_services', to: 'services#my_services'
  root to: 'pages#home'
  get 'profile/:id', to: 'pages#profile', :as => :profile

  get 'success/', to: 'bookings#success' 
  get 'my_profile/', to: 'pages#my_profile', :as => :my_profile

end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
    has_many :bookings
    validates :name, length: { in: 2..10, message: "Must be between 2 and 10 characters"}
    validates :species, inclusion: { in: ['Cat', 'Dog']} 
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  load_and_authorize_resource
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # Instead of indexing all pets, filtered to only show the pets owned by the current user
  def index
    @allpets = Pet.includes(:user).all
    @pets = []
    
    @allpets.each { |pet| 
      if pet.user_id == current_user.id
        @pets << pet
      end
      }
  end


  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # Automatically sets pet owner to the current user
  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def pet_params
    params.require(:pet).permit(:name, :user_id, :picture)
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :user_id, :species, :picture)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<div class="form-signin text-center container" >

<%= image_tag("logo.png", class: "mb-4")%>
<h2 class="h3 mb-3 font-weight-normal" >Tell us about your pet</h2>
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, class: "form-control", placeholder: "Pet's name"  %>
  </div>

  <div class="field">
    <%= form.select(:species, [['Cat', 'Cat'], ['Dog', 'Dog']], { :prompt => "Species"}, { :class => "form-control"}) %>

  </div>

 <br>
  <div class="field">
    <%= form.label "Show us a cute picture!"%>
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg', class: "form-control-file" %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Pets</h1>

  <div class="card-container">
      <% @pets.each do |pet| %>
      <%= link_to pet do%>
          <div class="prof-card">
              <div class="card-body">
                  <% if pet.picture.attached? %>
                    <%= image_tag pet.picture, class:"pet-image"  %>
                  <%elsif pet.species == "Dog" %>
                    <%= image_tag 'dog.png', class:"pet-image"%>
                  <% elsif pet.species =="Cat"%>
                    <%= image_tag 'cat.png', class:"pet-image"%>
                  <%end%>
              </div>
              <div class="card-body">
                  <h5 class="card-title"><%= pet.name %></h5>
                  <p><%= pet.species%></p>
              </div>
          </div>
          <%end%>
      <%end%>
  </div>

<%= link_to 'New Pet', new_pet_path, class: "btn btn-outline-info btn-lg" %>

app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

<%= link_to 'Cancel', pets_path %>

app/views/pets/show.html.erb
  <% if @pet.picture.attached? %>
    <%= image_tag @pet.picture, class:"pet-image"  %>
  <%elsif @pet.species == "Dog" %>
    <%= image_tag 'dog.png', class:"pet-image"%>
  <% elsif @pet.species =="Cat"%>
    <%= image_tag 'cat.png', class:"pet-image"%>
  <%end%>
  <p>
    <strong>Name:</strong>
    <%= @pet.name %>
  </p>

  <% if can? :manage, @pet %>
  <%= link_to 'Edit', edit_pet_path(@pet) %>
  <br>
  <%= link_to "Remove #{@pet.name}", @pet, method: :delete, data: { confirm: 'Are you sure?' } %>
  <br>
  <%end%>
  <%= link_to 'Back', pets_path %>