config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :bookings
  resources :services
  resources :pets
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/checkout', to: 'pages#checkout'
  get '/about', to: 'pages#about'
  get '/find', to: 'pages#find'
  get '/my_services', to: 'services#my_services'
  root to: 'pages#home'
  get 'profile/:id', to: 'pages#profile', :as => :profile

  get 'success/', to: 'bookings#success' 
  get 'my_profile/', to: 'pages#my_profile', :as => :my_profile

end

app/views/pages/_profile.html.erb
<%# If user has a picture, display it, otherwise, 
display the default user/nurse image 
- could add male/female field and render different images%>

<% if @user.picture.attached? %>
    <%= image_tag @user.picture, class:"user-image" %>
<%elsif @user.is_nurse?%>
    <%= image_tag 'nurse.png', class:"user-image"%>   
<%else%>
    <%= image_tag 'user.png', class:"user-image"%>
<%end%>

    <br>
    <h2>
    <%= @user.fname %> <%= @user.lname%>
    </h2>
    <br>


<%# If user is current user, show the whole address and give 
the option to edit the full address and login details,
if they are not the owner of the profile, only show
the user's suburb and state.  %>
<% if @user == current_user %>
    <p>
        <strong>Address:</strong><br>
        <%= @user.address.street rescue nil%><br>
        <%= @user.address.suburb rescue nil%>,
        <%= @user.address.state rescue nil%>
    </p>
    <%= link_to 'Edit Address', edit_address_path(@user.address) rescue nil %> <br>
    <%= link_to 'Edit Login Details', edit_user_registration_path %>

<% else %>
    <%= @user.address.address rescue nil%>
<%end%>

    <% if @user.is_nurse? && @user.services.length > 0%>    

<div class="services-list">
  <div class="services-header row mb-3">
    <div class="col-md-3">
      <strong>Service</strong>
    </div>
    <div class="col-md-6">
      <strong>Description</strong>
    </div>
    <div class="col-md-3">
      <strong>Price</strong>
    </div>
  </div>

<% @user.services.each do |service| %>
  <%= link_to service do %>
      <div class="row mb-3 service">
        <div class="col-md-3">
          <%= service.name %>
        </div>
        <div class="col-md-6">
          <%= service.description %>
        </div>
        <div class="col-md-3">
          <%= number_to_currency(service.price) %>
      </div>
  </div>
    <%end%>
  <% end %>
</div>



<%# If there are no services for the user, say so,
 and if the user is a nurse, give them the option to
create a new service, %>
    <%elsif @user.is_nurse? && @user.services.length == 0%>
<div class="content-container">
        <p> No services listed yet!  </p>
    <%end%>
    <% if @user.is_nurse? && @user == current_user %>  
      <%= link_to 'New Service', new_service_path, class: "btn btn-outline-info btn-lg" %>

    <%end%>
</div>

app/views/pages/about.html.erb
<p>Here I would like to have some information about Whiskr, what it is and how it works </p>
<p>Things like... </p>
<ul>
    <li> Nurse qualifications </li>
    <li> Nurse insurance </li>
    <li> Benefits of home calls </li>
    <li> Information for veterinarians </li>
</ul>

app/views/pages/find.html.erb
 <%# Look at Ransack gem for searching & sorting results, may also allow me to use paginate! %>
 <%# Displays the results for nurses in your searched area if there
 are any, otherwise, prompt the user to try again %>

 <% if @nurses.length > 0 %>
        <h2> Here are all the nurses near you... </h2>

        <div class="card-container">
            <% @nurses.each do |nurse| %>
                <%= link_to profile_path(nurse) do%>
                <div class="prof-card">
                    <div class="card-body">
                        <% if nurse.picture.attached? %>
                            <%= image_tag nurse.picture, class:"user-image" %>
                        <%else%>
                            <%= image_tag 'nurse.png', class:"user-image"%>
                        <%end%>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= nurse.fname %></h5>
                        <p> From <%= nurse.address.suburb%></p>
                    </div>
                </div>
                <%end%>
            <%end%>
        </div>

    <% else %>
        <p> Sorry... No results found...
        <br> Try searching nearby suburbs or your city.
        <br>You could also try including your state, eg. <i>'Marrickville, NSW'</i>
        </p>
            <div class="input-group mb-8">
                    <%= form_tag(find_path, method: 'get') do %>
                    <div class="input-group-append">
                        <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Suburb") %>
                        <%= submit_tag("Search", class: "input-group-text", id: "basic-addon2") %>
                        <% end %>
                     </div>
            </div>
    <% end %>

app/views/pages/home.html.erb
<div class="hero">
    <%= image_tag "hero-img2.jpg", class: "hero-img"%>
    <div class="header">
        <h1 class="title">whiskr</h1>

    </div>


</div>
<div class="notifications-home">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <div class="container marketing">
      <div class="row">

          <div class="col-lg-4 text-center">
            <%= image_tag 'signup.png', class: "rounded-circle spot", alt: "Clipboard Image"%>
              <h2>Sign Up</h2>
              <p>Join us as a Pet Parent or start helping pets as a Veterinary Nurse!</p>
              <p><%= link_to "Sign Up", :new_user_registration, class: "btn btn-secondary", role: "button" %></p>
          </div><!-- /.col-lg-4 -->

          <div class="col-lg-4 text-center">
            <%= image_tag 'nurse.png', class: "rounded-circle spot", alt: "Nurse Image"%>
              <h2>Find a Nurse</h2>
              <p>Find a qualified and insured mobile veterinary nurse in your area.</p>
        <div class="input-group center-bar">
        <%= form_tag(find_path, method: 'get') do %>
          <div class="input-group-append">
            <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Suburb") %>
            <%= submit_tag("Search", class: "input-group-text", id: "basic-addon2") %>
              <% end %>
        </div>
        </div>
          </div><!-- /.col-lg-4 -->

          <div class="col-lg-4 text-center">
            <%= image_tag 'about.png', class: "rounded-circle spot", alt: "About Image"%>              <h2>About</h2>
              <p>We help find care for pets in the comfort of their own home.</p>
              <p><%= link_to "Learn More", :about, class: "btn btn-secondary", role: "button" %></p>
          </div><!-- /.col-lg-4 -->

      </div><!-- /.row -->
    </div>

    <div class="row featurette spread odd">
      <div class="col-md-6">
        <h2 class="featurette-heading">Vet Nurses come to you. <span class="text-muted">It’s less scary at home.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-img">
        <%= image_tag 'catcubby.jpeg', class: "mini-hero right"%>
      </div>
    </div>

    <div class="row featurette">
      <div class="col-md-6 order-md-2">
        <h2 class="featurette-heading">Peace of mind. <span class="text-muted">In between hospital visits.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-img">
        <%= image_tag 'conepuppy.jpg', class: "mini-hero"%>      </div>
    </div>



  <p class="credits">  Icons made by <a href="https://www.flaticon.com/authors/icon-pond" title="Icon Pond">Icon Pond</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a> </p>

app/views/pages/my_profile.html.erb
    <%= render 'profile'%>

app/views/pages/profile.html.erb
<%= render 'profile'%>